# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz_Voz.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1123, 590)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        Form.setFont(font)
        self.pushButton_Audio = QtWidgets.QPushButton(Form)
        self.pushButton_Audio.setGeometry(QtCore.QRect(40, 350, 151, 41))
        self.pushButton_Audio.setObjectName("pushButton_Audio")
        self.label_RutaAudio = QtWidgets.QLabel(Form)
        self.label_RutaAudio.setGeometry(QtCore.QRect(220, 360, 491, 31))
        self.label_RutaAudio.setObjectName("label_RutaAudio")
        self.pushButton_Evaluar = QtWidgets.QPushButton(Form)
        self.pushButton_Evaluar.setGeometry(QtCore.QRect(30, 480, 181, 81))
        self.pushButton_Evaluar.setObjectName("pushButton_Evaluar")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 20, 521, 301))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_Audio = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_Audio.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_Audio.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Audio.setSpacing(1)
        self.verticalLayout_Audio.setObjectName("verticalLayout_Audio")
        self.pushButton_ReproducirAudio = QtWidgets.QPushButton(Form)
        self.pushButton_ReproducirAudio.setGeometry(QtCore.QRect(40, 410, 151, 41))
        self.pushButton_ReproducirAudio.setObjectName("pushButton_ReproducirAudio")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(570, 20, 521, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_Frecuencia = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_Frecuencia.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_Frecuencia.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Frecuencia.setSpacing(1)
        self.verticalLayout_Frecuencia.setObjectName("verticalLayout_Frecuencia")
        self.label_Status = QtWidgets.QLabel(Form)
        self.label_Status.setGeometry(QtCore.QRect(260, 510, 461, 21))
        self.label_Status.setObjectName("label_Status")
        self.radioButton_Hombre = QtWidgets.QRadioButton(Form)
        self.radioButton_Hombre.setGeometry(QtCore.QRect(910, 350, 141, 20))
        self.radioButton_Hombre.setObjectName("radioButton_Hombre")
        self.radioButton_Mujer = QtWidgets.QRadioButton(Form)
        self.radioButton_Mujer.setGeometry(QtCore.QRect(910, 400, 95, 16))
        self.radioButton_Mujer.setObjectName("radioButton_Mujer")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_Audio.setText(_translate("Form", "Grabar Audio "))
        self.label_RutaAudio.setText(_translate("Form", "Grabe Audio Primero"))
        self.pushButton_Evaluar.setText(_translate("Form", "Evaluar"))
        self.pushButton_ReproducirAudio.setText(_translate("Form", "Reproducir Audio"))
        self.label_Status.setText(_translate("Form", "Resultado"))
        self.radioButton_Hombre.setText(_translate("Form", "Hombre"))
        self.radioButton_Mujer.setText(_translate("Form", "Mujer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
