# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz_Voz.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1520, 771)
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        Form.setFont(font)
        self.pushButton_Audio = QtWidgets.QPushButton(Form)
        self.pushButton_Audio.setGeometry(QtCore.QRect(30, 50, 151, 41))
        self.pushButton_Audio.setObjectName("pushButton_Audio")
        self.label_RutaAudio = QtWidgets.QLabel(Form)
        self.label_RutaAudio.setGeometry(QtCore.QRect(190, 50, 891, 31))
        self.label_RutaAudio.setObjectName("label_RutaAudio")
        self.pushButton_Evaluar = QtWidgets.QPushButton(Form)
        self.pushButton_Evaluar.setGeometry(QtCore.QRect(90, 140, 621, 51))
        self.pushButton_Evaluar.setObjectName("pushButton_Evaluar")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(50, 300, 671, 391))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_Audio = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_Audio.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_Audio.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Audio.setSpacing(1)
        self.verticalLayout_Audio.setObjectName("verticalLayout_Audio")
        self.pushButton_ReproducirAudio = QtWidgets.QPushButton(Form)
        self.pushButton_ReproducirAudio.setGeometry(QtCore.QRect(210, 220, 351, 41))
        self.pushButton_ReproducirAudio.setObjectName("pushButton_ReproducirAudio")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(790, 300, 669, 389))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_Frecuencia = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_Frecuencia.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_Frecuencia.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Frecuencia.setSpacing(1)
        self.verticalLayout_Frecuencia.setObjectName("verticalLayout_Frecuencia")
        self.label_Status = QtWidgets.QLabel(Form)
        self.label_Status.setGeometry(QtCore.QRect(760, 150, 481, 21))
        self.label_Status.setObjectName("label_Status")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_Audio.setText(_translate("Form", "Grabar Audio "))
        self.label_RutaAudio.setText(_translate("Form", "..."))
        self.pushButton_Evaluar.setText(_translate("Form", "Evaluar"))
        self.pushButton_ReproducirAudio.setText(_translate("Form", "Reproducir Audio"))
        self.label_Status.setText(_translate("Form", "Resp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
